spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: false
  data-source:
    url: jdbc:postgresql://localhost:5433/michalsiron
    username: michalsiron
    password:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    enabled: true